version: '3.8'

services:

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server-qdrant
    ports:
      - "8001:80"
    environment:
      - QDRANT_URL=http://host.docker.internal:6333
      - QDRANT_API_KEY=a05cece8-7fce-4e60-972e-b28ece45cf3c
      - COLLECTION_NAME=emsal_uyap
      - EMBEDDING_MODEL=text-embedding-004
      - EMBEDDING_PROVIDER=gemini-transformer
      - GEMINI_API_KEY=AIzaSyCRgykLuJeSv-Qip6_Oh8Co0Y1sgfwnZvg
      # Search and access control settings
      - QDRANT_SEARCH_LIMIT=100
      - QDRANT_READ_ONLY=true
      # Use system CA certificates
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      # Logging environment variables
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - LOG_LEVEL=DEBUG
      - LOG_DIR=/app/logs
      - QDRANT_TIMEOUT=30
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      